/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmgba_free: (a: number, b: number) => void;
export const wasmgba_clear_save_dirty: (a: number) => void;
export const wasmgba_clear_watch: (a: number) => void;
export const wasmgba_debug_state: (a: number) => [number, number];
export const wasmgba_drain_audio: (a: number) => [number, number];
export const wasmgba_frame_count: (a: number) => number;
export const wasmgba_framebuffer: (a: number) => [number, number];
export const wasmgba_framebuffer_len: (a: number) => number;
export const wasmgba_framebuffer_ptr: (a: number) => number;
export const wasmgba_load_rom: (a: number, b: number, c: number) => void;
export const wasmgba_load_save_ram: (a: number, b: number, c: number) => void;
export const wasmgba_load_state: (a: number, b: number, c: number) => number;
export const wasmgba_new: () => number;
export const wasmgba_oam: (a: number) => [number, number];
export const wasmgba_pram: (a: number) => [number, number];
export const wasmgba_read16: (a: number, b: number) => number;
export const wasmgba_read8: (a: number, b: number) => number;
export const wasmgba_reset_save: (a: number) => void;
export const wasmgba_run_frame: (a: number) => void;
export const wasmgba_save_dirty: (a: number) => number;
export const wasmgba_save_ram: (a: number) => [number, number];
export const wasmgba_save_state: (a: number) => [number, number];
export const wasmgba_save_type: (a: number) => [number, number];
export const wasmgba_set_cheats: (a: number, b: number, c: number) => void;
export const wasmgba_set_keys: (a: number, b: number) => void;
export const wasmgba_set_turbo_mask: (a: number, b: number) => void;
export const wasmgba_set_watch: (a: number, b: number, c: number) => void;
export const wasmgba_sio_apply_remote_multiplay: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasmgba_sio_clear_trace: (a: number) => void;
export const wasmgba_sio_deliver_multiplay: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasmgba_sio_set_link: (a: number, b: number, c: number) => void;
export const wasmgba_sio_set_trace: (a: number, b: number) => void;
export const wasmgba_sio_take_outgoing: (a: number) => number;
export const wasmgba_sio_trace: (a: number) => [number, number];
export const wasmgba_vram: (a: number) => [number, number];
export const wasmgba_watch_log: (a: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
